[tool.poetry]
name = "capitalgram"
version = "0.1.0"
description = ""
authors = ["Mikko Ohtamaa <mikko@opensourcehacker.com>"]

[tool.poetry.dependencies]
python = "^3.7.2"
eth-utils = "^1.10.0"
dataclasses-json = "^0.5.4"
zstandard = "^0.15.2"
pandas = "^1.3.0"
pyarrow = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
