# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Build documentation
      run: |
        cd docs && poetry run make html && mv build/html ../build
    - name: Deploy to Netlify
      uses: danakim/gh-action-deploy-netlify@master
      with:
        AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        DEPLOY_PROD: true
