# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Netlify deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: 'poetry'
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        pip install poetry
    - name: Build documentation
      run: |
        cd docs && poetry run make html
    - name: Pre-check
      run: |
        mkdir /tmp/site
        cp docs/proxy-index.html /tmp/site/index.html
        cp -r docs/build/html /tmp/site/docs
        ls -lha /tmp/site
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: '/tmp/site'
        production-branch: master
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
        overwrites-pull-request-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
      timeout-minutes: 1