# Check that the latest PyPi release is kosher

name: Pip installation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-pip-install:

    runs-on: [self-hosted, TRADINGSTRATEGY]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Check pip install from PyPi works
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -U pip
        pip install trading-strategy
